/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppTimetableRouteImport } from './routes/_app.timetable'
import { Route as AppStudentsRouteImport } from './routes/_app.students'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppFeesRouteImport } from './routes/_app.fees'
import { Route as AppFacultyRouteImport } from './routes/_app.faculty'
import { Route as AppExamsRouteImport } from './routes/_app.exams'
import { Route as AppCoursesRouteImport } from './routes/_app.courses'
import { Route as AppAttendanceRouteImport } from './routes/_app.attendance'
import { Route as AppAdmissionsRouteImport } from './routes/_app.admissions'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTimetableRoute = AppTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsRoute = AppStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppFeesRoute = AppFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AppRoute,
} as any)
const AppFacultyRoute = AppFacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => AppRoute,
} as any)
const AppExamsRoute = AppExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AppRoute,
} as any)
const AppCoursesRoute = AppCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppAdmissionsRoute = AppAdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/admissions': typeof AppAdmissionsRoute
  '/attendance': typeof AppAttendanceRoute
  '/courses': typeof AppCoursesRoute
  '/exams': typeof AppExamsRoute
  '/faculty': typeof AppFacultyRoute
  '/fees': typeof AppFeesRoute
  '/settings': typeof AppSettingsRoute
  '/students': typeof AppStudentsRoute
  '/timetable': typeof AppTimetableRoute
}
export interface FileRoutesByTo {
  '/admissions': typeof AppAdmissionsRoute
  '/attendance': typeof AppAttendanceRoute
  '/courses': typeof AppCoursesRoute
  '/exams': typeof AppExamsRoute
  '/faculty': typeof AppFacultyRoute
  '/fees': typeof AppFeesRoute
  '/settings': typeof AppSettingsRoute
  '/students': typeof AppStudentsRoute
  '/timetable': typeof AppTimetableRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/admissions': typeof AppAdmissionsRoute
  '/_app/attendance': typeof AppAttendanceRoute
  '/_app/courses': typeof AppCoursesRoute
  '/_app/exams': typeof AppExamsRoute
  '/_app/faculty': typeof AppFacultyRoute
  '/_app/fees': typeof AppFeesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/students': typeof AppStudentsRoute
  '/_app/timetable': typeof AppTimetableRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admissions'
    | '/attendance'
    | '/courses'
    | '/exams'
    | '/faculty'
    | '/fees'
    | '/settings'
    | '/students'
    | '/timetable'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admissions'
    | '/attendance'
    | '/courses'
    | '/exams'
    | '/faculty'
    | '/fees'
    | '/settings'
    | '/students'
    | '/timetable'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/admissions'
    | '/_app/attendance'
    | '/_app/courses'
    | '/_app/exams'
    | '/_app/faculty'
    | '/_app/fees'
    | '/_app/settings'
    | '/_app/students'
    | '/_app/timetable'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/timetable': {
      id: '/_app/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof AppTimetableRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students': {
      id: '/_app/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AppStudentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fees': {
      id: '/_app/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof AppFeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/faculty': {
      id: '/_app/faculty'
      path: '/faculty'
      fullPath: '/faculty'
      preLoaderRoute: typeof AppFacultyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exams': {
      id: '/_app/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof AppExamsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/courses': {
      id: '/_app/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof AppCoursesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance': {
      id: '/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admissions': {
      id: '/_app/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AppAdmissionsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdmissionsRoute: typeof AppAdmissionsRoute
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppCoursesRoute: typeof AppCoursesRoute
  AppExamsRoute: typeof AppExamsRoute
  AppFacultyRoute: typeof AppFacultyRoute
  AppFeesRoute: typeof AppFeesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStudentsRoute: typeof AppStudentsRoute
  AppTimetableRoute: typeof AppTimetableRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdmissionsRoute: AppAdmissionsRoute,
  AppAttendanceRoute: AppAttendanceRoute,
  AppCoursesRoute: AppCoursesRoute,
  AppExamsRoute: AppExamsRoute,
  AppFacultyRoute: AppFacultyRoute,
  AppFeesRoute: AppFeesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStudentsRoute: AppStudentsRoute,
  AppTimetableRoute: AppTimetableRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
